ros-industrial/industrial_calibration

industrial_extrinsic_cal/CMakeLists.txt, industrial_extrinsic_cal/include/industrial_extrinsic_cal/ros_transform_interface.h, industrial_extrinsic_cal/src/calibration_job_definition.cpp, industrial_extrinsic_cal/src/ros_transform_interface.cpp
Clean and finished follow up to https://github.com/ros-industrial/industrial_calibration/pull/46
=> Fix CMakeLists.txt; Fix transform_interface: ros_camera_housing_bti

industrial_extrinsic_cal/urdf/calibration_transform_macro.xacro
=> Fix indentation in calibration transform macro

rgbd_depth_correction/CMakeLists.txt, rgbd_depth_correction/package.xml
=> Fix missing dependency on openni2_camera

.travis.yml
This should make Travis build work!
:construction: Don't merge until Travis works
=> Disable tests on Travis CI builds

.travis.yml, README.md, caljob_creator/CMakeLists.txt, industrial_extrinsic_cal/CMakeLists.txt, industrial_extrinsic_cal/include/industrial_extrinsic_cal/circle_detector.hpp, industrial_extrinsic_cal/src/camera_yaml_parser.cpp, industrial_extrinsic_cal/src/ros_camera_observer.cpp, intrinsic_cal/CMakeLists.txt, intrinsic_cal/src/rail_cal.cpp, rgbd_depth_correction/CMakeLists.txt, target_finder/CMakeLists.txt
:warning: Still in construction!
=> [WIP] Kinetic fixes

industrial_extrinsic_cal/src/ros_camera_observer.cpp
A few fairly minor changes:
- For the modified circle grid target, separate calls are used for keypoint detection and overall circle grid detection, and it was assumed that they would have the exact same x and y coordinates. ~~That assumption is no longer made and keypoints are matched to pattern centers by comparing distances.~~ Verified that this assumption is accurate if the correct blob/circle detector is sent to both calls.
- The image acquisition no longer blocks indefinitely in `triggerCamera()`, but times-out after 5 seconds and errors if no image was acquired on the topic.
=> Changes to ROSCameraObserver for modified circle grid target

rgbd_depth_correction/CMakeLists.txt, rgbd_depth_correction/package.xml, rgbd_depth_correction/src/depth_correction.cpp
Followup from the discussions in PR #76 and with @drchrislewis.
=> Remove `openni2_camera` build dependency

industrial_extrinsic_cal/include/industrial_extrinsic_cal/observation_scene.h
add the missing `~` to the destructor and add a constructor with no input
=> fixes issue #132

industrial_extrinsic_cal/include/industrial_extrinsic_cal/ros_triggers.h
replace ROS_ERROR with ROS_INFO in waitForTrigger method of ROSParamTrigger
=> fixes issue #130

.rosinstall, README.md
=> Fixes robo-cylinder build dependency

applicable_pose_generator/CMakeLists.txt, calibration_guis/CMakeLists.txt, caljob_creator/CMakeLists.txt, industrial_extrinsic_cal/CMakeLists.txt, intrinsic_cal/CMakeLists.txt, rgbd_depth_correction/CMakeLists.txt, stand_alone_gui/CMakeLists.txt, target_finder/CMakeLists.txt
Related to https://github.com/ros-industrial/ros_industrial_issues/issues/67
=> Increase minimum CMake version to allow builds on Focal Fossa (Noetic)

examples/extrinsic_hand_eye.cpp
Changes per commit message to simplify the hand-eye example
=> Simplified hand eye example

examples/data/test_set_10x10/cal_data.yaml, examples/data/test_set_charuco/cal_data.yaml, examples/extrinsic_hand_eye.cpp
=> Moved static camera flag to calibration configuration file

CMakeLists.txt, analysis/CMakeLists.txt, core/CMakeLists.txt, examples/CMakeLists.txt, optimizations/CMakeLists.txt, target_finders/CMakeLists.txt, target_finders/opencv/CMakeLists.txt, test/CMakeLists.txt
=> Various CMake Updates

core/include/industrial_calibration/core/target_finder.h
=> Removed cout print from target finder base class

gui/include/industrial_calibration/gui/extrinsic_hand_eye_calibration_widget.h, gui/src/app/extrinsic_hand_eye_calibration_app.cpp, gui/src/extrinsic_hand_eye_calibration_widget.cpp, gui/src/extrinsic_hand_eye_calibration_widget.ui
=> Updated GUI to use QMainWindow

core/src/camera_intrinsics.cpp, optimizations/src/camera_intrinsic.cpp
=> Updated stream operator for camera intrinsics

optimizations/include/industrial_calibration/optimizations/camera_intrinsic.h, optimizations/src/camera_intrinsic.cpp
Various updates to the camera intrinsic optimization, per the commit messages
=> Camera intrinsic optimization updates

gui/CMakeLists.txt, gui/include/industrial_calibration/gui/target_finder.h, gui/src/target_finder.cpp, gui/src/target_finder.ui
This PR adds a widget for choosing and configuring a target finder
=> Added target finder widget

gui/include/industrial_calibration/gui/camera_intrinsic_calibration_widget.h, gui/include/industrial_calibration/gui/extrinsic_hand_eye_calibration_widget.h, gui/src/camera_intrinsic_calibration_widget.cpp, gui/src/extrinsic_hand_eye_calibration_widget.cpp
=> Add exit question dialog box to calibration widgets

examples/CMakeLists.txt, gui/CMakeLists.txt
This PR installs the executables from this project in to folder that is accessible by the `ros2 run` and `rosrun` commands
=> Installed executables in directory accessible by ROS

.clang-format, analysis/src/statistics.cpp, core/include/industrial_calibration/core/target_finder.h, examples/noise_qualification_2d.cpp, gui/src/app/camera_intrinsic_calibration_app.cpp, gui/src/app/extrinsic_hand_eye_calibration_app.cpp, gui/src/camera_intrinsic_calibration_widget.cpp, gui/src/extrinsic_hand_eye_calibration_widget.cpp, gui/src/target_finder.cpp, optimizations/include/industrial_calibration/optimizations/local_parameterization.h, optimizations/src/camera_intrinsic.cpp, optimizations/src/covariance_analysis.cpp, optimizations/src/covariance_types.cpp, optimizations/src/dh_chain_kinematic_calibration.cpp, target_finders/opencv/src/circle_detector.cpp, target_finders/opencv/src/modified_circle_grid_target_finder.cpp, target_finders/opencv/src/utils.cpp, test/pnp_utest.cpp, test/serialization_utest.cpp
Changes per commit message to clang format
=> Do not allow short if statements on single line

gui/src/extrinsic_hand_eye_calibration_widget.cpp
=> Fix check of pose file existence in extrinsic hand eye calibration widget

docker/docker-compose.override.yml, docker/docker-compose.yml
=> Minor Docker Updates

optimizations/src/extrinsic_hand_eye.cpp
Currently, the extrinsic hand-eye calibration result is serialized with the translation and RPY vectors, mostly for easier integration with URDF format. However, sometimes the quaternion representation of the rotation is needed instead, and extracting the quaternion from the serialized RPY values is challenging and can be ambiguous. This PR adds serialization of the full transform under the keys `camera_mount_to_camera` and `target_mount_to_target`, which provides both the translation and the quaternion. In a future (major) version release, we can get rid of the duplicate `camera_mount_to_camera_pos` and `target_mount_to_target_pos` keys.
=> Update to extrinsic hand eye result serialization
