- intrinsic_cal/CMakeLists.txt
Fixes configuration error:
```cmake
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:296 (message):
catkin_package() include dir 'include' does not exist relative to
'/home/victor/HiveSync/catkin_workspace/src/industrial_calibration/intrinsic_cal'
Call Stack (most recent call first):
/opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
industrial_calibration/intrinsic_cal/CMakeLists.txt:97 (catkin_package)
-- Configuring incomplete, errors occurred!
See also "/home/victor/HiveSync/catkin_workspace/build/CMakeFiles/CMakeOutput.log".
See also "/home/victor/HiveSync/catkin_workspace/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```
> Include directory does not exist

- caljob_creator/CMakeLists.txt
- caljob_creator/package.xml
- industrial_extrinsic_cal/CMakeLists.txt
- industrial_extrinsic_cal/package.xml
- intrinsic_cal/CMakeLists.txt
- intrinsic_cal/package.xml
- rgbd_depth_correction/CMakeLists.txt
- rgbd_depth_correction/package.xml
- target_finder/CMakeLists.txt
- target_finder/package.xml
Major changes:
- remove boilerplate from all manifests and build scripts
- checked and corrected dependency declarations
- fixed up `find_package(..)` usage for Ceres, Boost, OpenCV (now requires OpenCV v2)
- fixed up Yaml-Cpp detection (uses proper PkgConfig scripts now) (#14)
- fixed up `catkin_package(..)` statements (proper `(CATKIN_)DEPENDS` etc)
- fixed up include path config (#13)
- added install rules for all targets, launch files, yaml & rviz configs, etc (#12)
- made building tests (`industrial_extrinsic_cal`) conditional, based on `CATKIN_ENABLE_TESTING`
With the above changes `catkin_lint -W2` errors / warnings are down from 120+ to something like 15 (most of which are about target names being not unique enough).
Tested building on both 32 and 64 bit Ubuntu Trusty - Indigo …
> Cleanup of package manifests and build scripts

- industrial_extrinsic_cal/src/nodes/ros_robot_scene_trigger_action_server.cpp
MoveIt generates a `manipulator` kinematic chain by default (all lower-case).
:warning: The down-side of this PR is that every package using the `industrial_calibration` package will need to change it's kinematic chain from `Manipulator` to `manipulator`.
> Change Manipulator to manipulator

- industrial_extrinsic_cal/CMakeLists.txt
I don't know what this is for but because of this the compilation fails on my (64 bits) machine.
Tested on Chris computer, compilation works on a 32 bits machine too after the fix.
```
[ 57%] Building CXX object industrial_calibration/industrial_extrinsic_cal/CMakeFiles/mono_ex_cal.dir/src/nodes/mono_ex_cal.cpp.o
c++: fatal error: no input files
compilation terminated.
/bin/sh: 1: -fPIC: not found
make[2]: *** [industrial_calibration/industrial_extrinsic_cal/CMakeFiles/mono_ex_cal.dir/src/nodes/mono_ex_cal.cpp.o] Erreur 127
[ 57%] [ 57%] make[1]: *** [industrial_calibration/industrial_extrinsic_cal/CMakeFiles/mono_ex_cal.dir/all] Erreur 2
make[1]: *** Attente des tâches non terminées....[ 57%] 
[ 57%] [ 57%] Built target _intrinsic_cal_generate_messages_check_deps_rail_ical_run
Built …
```
> Fix CMakeLists.txt

- rgbd_depth_correction/CMakeLists.txt
- rgbd_depth_correction/include/depth_calibration/depth_calibration.h
- rgbd_depth_correction/launch/calibrate.launch
- rgbd_depth_correction/launch/correction.launch
- rgbd_depth_correction/package.xml
- rgbd_depth_correction/src/depth_calibration.cpp
- rgbd_depth_correction/src/depth_correction.cpp
- rgbd_depth_correction/yaml/camera_scene_cameras.yaml
@drchrislewis, please review.  This includes some code cleanup but primarily fixes depth_calibration.cpp to correctly handle special cases (NaN's in the point cloud, large stddev in target pose calculation, etc.).
> Rgbd fixes

- industrial_extrinsic_cal/package.xml
there is no "camera_aravis" package in indigo.
I made #82 . Please see that for more info.
> [fix] fix run dependence on indigo-devel

- industrial_extrinsic_cal/package.xml
- rgbd_depth_correction/src/depth_calibration.cpp
- rgbd_depth_correction/src/depth_correction.cpp
This was the only thing that caused a build error when trying to build the kinetic branch.
> Fixed build errors caused by 'isnan' not being declared in this scope

- .travis.yml
- industrial_extrinsic_cal/CMakeLists.txt
the tests in package industrial_extrinsic_cal were not finishing which caused travis to timeout and fail.  This is a temporary solution and we should figure out why the tests are not completing. However we should not let this get in the way of performing CI. Reference issue #99.
> remove tests from industrial_extrinsic_cal package

- .travis.yml
- industrial_extrinsic_cal/CMakeLists.txt
- industrial_extrinsic_cal/package.xml
This PR makes `industrial_calibration` binary release ready.
Address https://github.com/ros-industrial/industrial_calibration/issues/32. 
And even more, with this PR merged in, this package will become ready for binary release IMO.
- As noted there, binary of  `libceres-dev` has been available for 2 years already. Add some more missing dependency
- On my forked repo,
- [I confirmed that this PR builds on Travis CI](https://travis-ci.org/130s/industrial_calibration/jobs/265673122#L756).
```
-- Found Ceres version 1.8.0: /usr/include;/usr/include/eigen3;/usr/include
```
- ROS pre-release test failed only because the testcases still seem to have some issues (that's why tests are disabled for Travis CI https://github.com/ros-industrial/industrial_calibration/pull/81).
> [indigo] Use ceres binary 

- industrial_extrinsic_cal/include/industrial_extrinsic_cal/ros_camera_observer.h
- industrial_extrinsic_cal/src/ros_camera_observer.cpp
This adds an option in `ROSCameraObserver` for a user to specify that the image sent to the opencv pattern detector should be first normalized. I've found this is sometimes necessary because the whole image might have good contrast, but the desired region-of-interest does not, and so some further processing is needed after the subimage is extracted.
@drchrislewis let me know what you think. Also, what would be the recommended way to document the new parameter?
Thanks!
> Option to normalize the detection image

- industrial_extrinsic_cal/src/camera_yaml_parser.cpp
- industrial_extrinsic_cal/src/ros_camera_observer.cpp
@drchrislewis, please review. This PR adds the option to pull camera intrinsic parameters from the 'camera_info' topic and adds support for cameras that have multiple lenses (ir, rgb, left, right, etc.).  It also adds the cv::CALIB_CB_CLUSTERING option to the modified circle grid detector which gives better detection results for smaller sized grids.
> Fixed pulling of camera intrinsics from 'camera_info' topic

- industrial_extrinsic_cal/launch/rangeNmono.launch
- industrial_extrinsic_cal/launch/range_camera_excal.launch
- target_finder/launch/dual_tl_wg.launch
This PR fixes https://github.com/ros-industrial/industrial_training/issues/220 issue.
Environment:
- OS: Ubuntu 16.04
- ROS: Kinetic
> Replace `xacro.py` to `xacro --inorder`

- .travis.yml
- README.md
- industrial_calibration.rosinstall
- industrial_extrinsic_cal/package.xml
- intrinsic_cal/package.xml
- rgbd_depth_correction/package.xml
- target_finder/package.xml
Past discussion in #109 and [#62](https://github.com/ros-industrial/industrial_calibration/pull/62#issuecomment-156073773) seemed to converge on using the ceres binary dependency, but `kinetic-devel` still has a dependency on `ceres-solver`. As it builds fine with the system ceres package, any reason we shouldn't switch this dependency?
> Use ceres binary dependency

- industrial_extrinsic_cal/CMakeLists.txt
- intrinsic_cal/CMakeLists.txt
- rgbd_depth_correction/CMakeLists.txt
- target_finder/CMakeLists.txt
This avoids it showing up as a build error in IDEs such as QTCreator. Here is the description of the types from the CMake Docs
(none)         = Important information
STATUS         = Incidental information
> Change Ceres/OpenCV version message to STATUS type

- CMakeLists.txt
- examples/extrinsic_hand_eye.cpp
- include/industrial_calibration/optimizations/analysis/extrinsic_hand_eye_calibration_analysis.h
- include/industrial_calibration/optimizations/analysis/projection.h
- src/optimizations/analysis/extrinsic_hand_eye_calibration_analysis.cpp
- src/optimizations/analysis/projection.cpp
This PR moves several extrinsic hand-eye calibration analysis utilities out of the demo into a separate file that can be re-used by applications.
This PR also adds the capability of computing 3D reprojection error of the observed 2D image features onto the calibrated target plane. The intent of this PR is to give users additional feedback about the accuracy of the calibration in "world" units that can be more easily understood and interpreted, compared to the currently reported pixel error.
```diff
Initial cost?: 117.243 (pixels per dot)
Final cost?: 1.14589 (pixels per dot)
+  3D reprojection error statistics:
+ 	 Mean +/- Std. Dev. (m): 0.00289945 +/- 0.0016792
+	 Min (m): 4.26119e-05
+ 	 Max (m): 0.0150042
```
```diff
Did converge?: 1
Initial cost?: 15.7898 (pixels per dot)
Final …
```
> Hand-eye calibration analysis update and addition of 3D projection analysis

- optimizations/src/camera_intrinsic.cpp
- optimizations/src/dh_chain_kinematic_calibration.cpp
- optimizations/src/extrinsic_hand_eye.cpp
- optimizations/src/extrinsic_multi_static_camera.cpp
- optimizations/src/pnp.cpp
This PR updates the optimizations to compute covariance with options that make the computation more robust to rank deficiency. It also adds try-catch blocks around the covariance computation to still return results from successful optimizations where the covariance can't be computed for some reason
> Covariance update

- gui/include/industrial_calibration/gui/camera_intrinsic_calibration_widget.h
- gui/include/industrial_calibration/gui/extrinsic_hand_eye_calibration_widget.h
- gui/src/app/camera_intrinsic_calibration_app.cpp
- gui/src/app/extrinsic_hand_eye_calibration_app.cpp
- gui/src/camera_intrinsic_calibration_widget.cpp
- gui/src/extrinsic_hand_eye_calibration_widget.cpp
This PR exposes methods in the calibration widgets to allow them to be used in a headless context
> Expose methods in calibration widgets

- gui/include/industrial_calibration/gui/camera_intrinsic_calibration_widget.h
- gui/src/app/camera_intrinsic_calibration_app.cpp
- gui/src/camera_intrinsic_calibration_widget.cpp
- gui/src/camera_intrinsic_calibration_widget.ui
This PR adds a button to the camera intrinsic calibration GUI to save the results to a YAML file in a [format compatible with ROS](https://wiki.ros.org/camera_calibration_parsers#File_formats)
> Added serialization to ROS format for camera intrinsic calibration app

- README.md
I was excited to see the redesign was finished, but I couldn't find the ROS interfaces.  Especially since this repo historically included the ROS interfaces, I thought it might be good to document their new locations on the README.
> README: Add link to ROS interfaces

- gui/src/app/camera_intrinsic_calibration_app.cpp
- gui/src/app/extrinsic_hand_eye_calibration_app.cpp
This PR adds checks on the command line arguments to the calibration applications to ensure that the provided arguments are regular files before attempting to load and utilize them as such. This helps prevent problems when running the executables via `ros2 run` which always appends `--ros-args` to the end of the provided command line arguments
> Updated file checks for application arguments

- examples/kinematic_calibration.cpp
The ``_has_include`` is used across other files where <filesystem> is included. GNUC doesn't act out nicely with clang
> ensure works with clang compiler

- examples/kinematic_calibration.cpp
Resolves a linker error when building kinematic_calibration.cpp related to std::experimental::filesystem.
Part of the error resolved:
```kinematic_calibration.cpp:(.text+0x54e8): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'```
> Resolved linker issue with kinematic_calibration.cpp

- .github/workflows/clang_format.yml
- .github/workflows/cmake_format.yml
- .github/workflows/ubuntu.yml
As of April 15, 2025, Ubuntu 20.04 LTS runner images have been [deprecated](https://github.com/actions/runner-images/issues/11101).
This updates the clang and cmake format workflows to use a 22.04 runner image.
> Updated clang and cmake workflows to use 22.04 runner images

- .github/workflows/docker.yml
- docker/Dockerfile
- docker/docker-compose.yml
- docker/extrinsic_calibration_gui.sh
- docker/intrinsic_calibration_gui.sh
[Added Dockerfile and docker compose files](https://github.com/ros-industrial/industrial_calibration/commit/d4063819a7e663b82d596f5e33ad3548e1fbd8f6)
Addresses #208.
To overwrite the entrypoint, uncomment the entrypoint field in docker/docker-compose.yml.
> Added Dockerfile and docker compose files
